### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by xxxZer0xxx** [mpapenbr/goirsdk#22]
## ❓ Question

Hi, 

could you write small example uses of the goirsdk? I would like to use it to maybe build myself a simple overlay and track some data. But I don't really get how I get started. Any Input would be appreciated.

**Comment by mpapenbr** [comment]
Good point. 
As of now I can only offer to have a look here: https://github.com/mpapenbr/go-racelogger/blob/9871a363ed220a61646369d16865f293d5379a9d/internal/racelogger.go#L326

This is the main loop for my racelogger. The irsk-API is setup in setupWatchdog. Afterwards it is  basically just looping around line 377. When this method returns with ok there is data available. 

Getting data out of the API is here, for example: https://github.com/mpapenbr/go-racelogger/blob/9871a363ed220a61646369d16865f293d5379a9d/internal/processor/session.go#L46

**Comment by xxxZer0xxx** [comment]
Ok thank you, that's a start.

However I cannot get the package installed. When I use  
`go install github.com/mpapenbr/goirsdk/irsdk@latest`
I get the message:     
`module github.com/mpapenbr/goirsdk@latest found (v0.5.1), but does not contain package github.com/mpapenbr/goirsdk`

Am I doing something wrong?

**Comment by mpapenbr** [comment]
Hmm, I don't think you need to install it. I use it this way in the racelogger:

go.mod: https://github.com/mpapenbr/go-racelogger/blob/9871a363ed220a61646369d16865f293d5379a9d/go.mod#L16

In a module:
processor.go: https://github.com/mpapenbr/go-racelogger/blob/9871a363ed220a61646369d16865f293d5379a9d/internal/racelogger.go#L14C1-L15C36

```
import (
...
	"github.com/mpapenbr/goirsdk/irsdk"
	"github.com/mpapenbr/goirsdk/yaml"
...
)
```
